// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroupSet(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateGroupSet'](arg1, arg2, arg3);
}

export function CreateLibrary(arg1, arg2) {
  return window['go']['backend']['App']['CreateLibrary'](arg1, arg2);
}

export function CreateTag(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateTag'](arg1, arg2, arg3, arg4);
}

export function CreateVaultFolder(arg1) {
  return window['go']['backend']['App']['CreateVaultFolder'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['backend']['App']['DeleteEntry'](arg1);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['backend']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteGroupSet(arg1) {
  return window['go']['backend']['App']['DeleteGroupSet'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['backend']['App']['DeleteTag'](arg1);
}

export function DeleteVaultFile(arg1) {
  return window['go']['backend']['App']['DeleteVaultFile'](arg1);
}

export function DeleteVaultFolder(arg1) {
  return window['go']['backend']['App']['DeleteVaultFolder'](arg1);
}

export function ExportBackup() {
  return window['go']['backend']['App']['ExportBackup']();
}

export function ExportLibraryCSV(arg1) {
  return window['go']['backend']['App']['ExportLibraryCSV'](arg1);
}

export function ExportMediaAsset(arg1, arg2) {
  return window['go']['backend']['App']['ExportMediaAsset'](arg1, arg2);
}

export function GetAllTags() {
  return window['go']['backend']['App']['GetAllTags']();
}

export function GetAllVaultFiles() {
  return window['go']['backend']['App']['GetAllVaultFiles']();
}

export function GetDatabaseStats() {
  return window['go']['backend']['App']['GetDatabaseStats']();
}

export function GetEntries(arg1) {
  return window['go']['backend']['App']['GetEntries'](arg1);
}

export function GetEntriesByTag(arg1, arg2) {
  return window['go']['backend']['App']['GetEntriesByTag'](arg1, arg2);
}

export function GetFiles(arg1) {
  return window['go']['backend']['App']['GetFiles'](arg1);
}

export function GetGroupSets(arg1) {
  return window['go']['backend']['App']['GetGroupSets'](arg1);
}

export function GetLibraries() {
  return window['go']['backend']['App']['GetLibraries']();
}

export function GetLibrary(arg1) {
  return window['go']['backend']['App']['GetLibrary'](arg1);
}

export function GetTagsForEntry(arg1) {
  return window['go']['backend']['App']['GetTagsForEntry'](arg1);
}

export function ImportFile(arg1) {
  return window['go']['backend']['App']['ImportFile'](arg1);
}

export function ImportLegacyCSV(arg1) {
  return window['go']['backend']['App']['ImportLegacyCSV'](arg1);
}

export function MoveVaultFile(arg1, arg2) {
  return window['go']['backend']['App']['MoveVaultFile'](arg1, arg2);
}

export function PromptAndUploadVaultFile(arg1) {
  return window['go']['backend']['App']['PromptAndUploadVaultFile'](arg1);
}

export function RenameVaultFile(arg1, arg2) {
  return window['go']['backend']['App']['RenameVaultFile'](arg1, arg2);
}

export function RenameVaultFolder(arg1, arg2) {
  return window['go']['backend']['App']['RenameVaultFolder'](arg1, arg2);
}

export function RunDatabaseMaintenance() {
  return window['go']['backend']['App']['RunDatabaseMaintenance']();
}

export function SaveEntry(arg1) {
  return window['go']['backend']['App']['SaveEntry'](arg1);
}

export function SetCoverImage(arg1) {
  return window['go']['backend']['App']['SetCoverImage'](arg1);
}

export function SetLibraryCover(arg1) {
  return window['go']['backend']['App']['SetLibraryCover'](arg1);
}

export function StreamHandler(arg1, arg2) {
  return window['go']['backend']['App']['StreamHandler'](arg1, arg2);
}

export function UpdateEntryTags(arg1, arg2) {
  return window['go']['backend']['App']['UpdateEntryTags'](arg1, arg2);
}

export function UpdateFileOrder(arg1) {
  return window['go']['backend']['App']['UpdateFileOrder'](arg1);
}

export function UpdateLibrary(arg1) {
  return window['go']['backend']['App']['UpdateLibrary'](arg1);
}

export function UpdateOrder(arg1) {
  return window['go']['backend']['App']['UpdateOrder'](arg1);
}

export function UpdateTag(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateTag'](arg1, arg2, arg3, arg4, arg5);
}
