// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {http} from '../models';

export function CreateGroupSet(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CreateLibrary(arg1:string,arg2:string):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function CreateVaultFolder(arg1:string):Promise<void>;

export function DeleteEntry(arg1:number):Promise<void>;

export function DeleteFile(arg1:number,arg2:number):Promise<void>;

export function DeleteGroupSet(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteVaultFile(arg1:number):Promise<void>;

export function DeleteVaultFolder(arg1:string):Promise<void>;

export function ExportLibraryCSV(arg1:number):Promise<string>;

export function ExportMediaAsset(arg1:number,arg2:string):Promise<void>;

export function GetAllTags():Promise<Array<backend.Tag>>;

export function GetAllVaultFiles():Promise<Array<backend.File>>;

export function GetEntries(arg1:number):Promise<Array<backend.Entry>>;

export function GetEntriesByTag(arg1:number,arg2:number):Promise<Array<backend.Entry>>;

export function GetFiles(arg1:number):Promise<Array<backend.File>>;

export function GetGroupSets(arg1:number):Promise<Array<backend.GroupSet>>;

export function GetLibraries():Promise<Array<backend.Library>>;

export function GetLibrary(arg1:number):Promise<backend.Library>;

export function GetTagsForEntry(arg1:number):Promise<Array<backend.Tag>>;

export function ImportFile(arg1:number):Promise<void>;

export function ImportLegacyCSV(arg1:number):Promise<string>;

export function MoveVaultFile(arg1:number,arg2:string):Promise<void>;

export function PromptAndUploadVaultFile(arg1:string):Promise<void>;

export function RenameVaultFile(arg1:number,arg2:string):Promise<void>;

export function RenameVaultFolder(arg1:string,arg2:string):Promise<void>;

export function SaveEntry(arg1:backend.Entry):Promise<void>;

export function SetCoverImage(arg1:number):Promise<void>;

export function SetLibraryCover(arg1:number):Promise<void>;

export function StreamHandler(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function UpdateEntryTags(arg1:number,arg2:Array<number>):Promise<void>;

export function UpdateFileOrder(arg1:Array<backend.File>):Promise<void>;

export function UpdateLibrary(arg1:backend.Library):Promise<void>;

export function UpdateOrder(arg1:Array<backend.Entry>):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;
