// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteMediaAsset(arg1) {
  return window['go']['main']['App']['DeleteMediaAsset'](arg1);
}

export function DeleteMediaGroup(arg1) {
  return window['go']['main']['App']['DeleteMediaGroup'](arg1);
}

export function DownloadBackup(arg1) {
  return window['go']['main']['App']['DownloadBackup'](arg1);
}

export function ExportMediaAsset(arg1, arg2) {
  return window['go']['main']['App']['ExportMediaAsset'](arg1, arg2);
}

export function GetAllLibraryAssets() {
  return window['go']['main']['App']['GetAllLibraryAssets']();
}

export function GetCompendiumData() {
  return window['go']['main']['App']['GetCompendiumData']();
}

export function GetEntries(arg1) {
  return window['go']['main']['App']['GetEntries'](arg1);
}

export function GetEntryImage(arg1) {
  return window['go']['main']['App']['GetEntryImage'](arg1);
}

export function GetMediaAssets(arg1) {
  return window['go']['main']['App']['GetMediaAssets'](arg1);
}

export function GetMediaGroups(arg1) {
  return window['go']['main']['App']['GetMediaGroups'](arg1);
}

export function ImportLegacyCSV() {
  return window['go']['main']['App']['ImportLegacyCSV']();
}

export function SaveEntry(arg1) {
  return window['go']['main']['App']['SaveEntry'](arg1);
}

export function SaveMediaAsset(arg1, arg2) {
  return window['go']['main']['App']['SaveMediaAsset'](arg1, arg2);
}

export function SaveMediaGroup(arg1) {
  return window['go']['main']['App']['SaveMediaGroup'](arg1);
}

export function UpdateAssetOrder(arg1) {
  return window['go']['main']['App']['UpdateAssetOrder'](arg1);
}

export function UpdateCompendiumData(arg1) {
  return window['go']['main']['App']['UpdateCompendiumData'](arg1);
}

export function UpdateOrder(arg1) {
  return window['go']['main']['App']['UpdateOrder'](arg1);
}
