// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroupSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateGroupSet'](arg1, arg2, arg3);
}

export function CreateLibrary(arg1, arg2) {
  return window['go']['main']['App']['CreateLibrary'](arg1, arg2);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteGroupSet(arg1) {
  return window['go']['main']['App']['DeleteGroupSet'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportLibraryCSV(arg1) {
  return window['go']['main']['App']['ExportLibraryCSV'](arg1);
}

export function ExportMediaAsset(arg1, arg2) {
  return window['go']['main']['App']['ExportMediaAsset'](arg1, arg2);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetEntries(arg1) {
  return window['go']['main']['App']['GetEntries'](arg1);
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetGroupSets(arg1) {
  return window['go']['main']['App']['GetGroupSets'](arg1);
}

export function GetLibraries() {
  return window['go']['main']['App']['GetLibraries']();
}

export function GetLibrary(arg1) {
  return window['go']['main']['App']['GetLibrary'](arg1);
}

export function GetTagsForEntry(arg1) {
  return window['go']['main']['App']['GetTagsForEntry'](arg1);
}

export function ImportFile(arg1) {
  return window['go']['main']['App']['ImportFile'](arg1);
}

export function ImportLegacyCSV(arg1) {
  return window['go']['main']['App']['ImportLegacyCSV'](arg1);
}

export function SaveEntry(arg1) {
  return window['go']['main']['App']['SaveEntry'](arg1);
}

export function SetCoverImage(arg1) {
  return window['go']['main']['App']['SetCoverImage'](arg1);
}

export function SetLibraryCover(arg1) {
  return window['go']['main']['App']['SetLibraryCover'](arg1);
}

export function StreamHandler(arg1, arg2) {
  return window['go']['main']['App']['StreamHandler'](arg1, arg2);
}

export function UpdateEntryTags(arg1, arg2) {
  return window['go']['main']['App']['UpdateEntryTags'](arg1, arg2);
}

export function UpdateFileOrder(arg1) {
  return window['go']['main']['App']['UpdateFileOrder'](arg1);
}

export function UpdateLibrary(arg1) {
  return window['go']['main']['App']['UpdateLibrary'](arg1);
}

export function UpdateOrder(arg1) {
  return window['go']['main']['App']['UpdateOrder'](arg1);
}

export function UpdateTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3, arg4);
}
