// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function CreateGroupSet(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CreateLibrary(arg1:string,arg2:string):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteEntry(arg1:number):Promise<void>;

export function DeleteFile(arg1:number):Promise<void>;

export function DeleteGroupSet(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function ExportLibraryCSV(arg1:number):Promise<string>;

export function ExportMediaAsset(arg1:number,arg2:string):Promise<void>;

export function GetAllTags():Promise<Array<main.Tag>>;

export function GetEntries(arg1:number):Promise<Array<main.Entry>>;

export function GetFiles(arg1:number):Promise<Array<main.File>>;

export function GetGroupSets(arg1:number):Promise<Array<main.GroupSet>>;

export function GetLibraries():Promise<Array<main.Library>>;

export function GetLibrary(arg1:number):Promise<main.Library>;

export function GetTagsForEntry(arg1:number):Promise<Array<main.Tag>>;

export function ImportFile(arg1:number):Promise<void>;

export function ImportLegacyCSV(arg1:number):Promise<string>;

export function SaveEntry(arg1:main.Entry):Promise<void>;

export function SetCoverImage(arg1:number):Promise<void>;

export function SetLibraryCover(arg1:number):Promise<void>;

export function UpdateEntryTags(arg1:number,arg2:Array<number>):Promise<void>;

export function UpdateFileOrder(arg1:Array<main.File>):Promise<void>;

export function UpdateLibrary(arg1:main.Library):Promise<void>;

export function UpdateOrder(arg1:Array<main.Entry>):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
