// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToEntry(arg1, arg2) {
  return window['go']['main']['App']['AddTagToEntry'](arg1, arg2);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteMediaAsset(arg1) {
  return window['go']['main']['App']['DeleteMediaAsset'](arg1);
}

export function DeleteMediaGroup(arg1) {
  return window['go']['main']['App']['DeleteMediaGroup'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DownloadBackup(arg1) {
  return window['go']['main']['App']['DownloadBackup'](arg1);
}

export function ExportMediaAsset(arg1, arg2) {
  return window['go']['main']['App']['ExportMediaAsset'](arg1, arg2);
}

export function GetAllLibraryAssets() {
  return window['go']['main']['App']['GetAllLibraryAssets']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetCompendiumData() {
  return window['go']['main']['App']['GetCompendiumData']();
}

export function GetEntries(arg1) {
  return window['go']['main']['App']['GetEntries'](arg1);
}

export function GetEntryImage(arg1) {
  return window['go']['main']['App']['GetEntryImage'](arg1);
}

export function GetMediaAssets(arg1) {
  return window['go']['main']['App']['GetMediaAssets'](arg1);
}

export function GetMediaGroups(arg1) {
  return window['go']['main']['App']['GetMediaGroups'](arg1);
}

export function GetTagsForEntry(arg1) {
  return window['go']['main']['App']['GetTagsForEntry'](arg1);
}

export function ImportLegacyCSV() {
  return window['go']['main']['App']['ImportLegacyCSV']();
}

export function RemoveTagFromEntry(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromEntry'](arg1, arg2);
}

export function SaveEntry(arg1) {
  return window['go']['main']['App']['SaveEntry'](arg1);
}

export function SaveMediaAsset(arg1, arg2) {
  return window['go']['main']['App']['SaveMediaAsset'](arg1, arg2);
}

export function SaveMediaGroup(arg1) {
  return window['go']['main']['App']['SaveMediaGroup'](arg1);
}

export function UpdateAssetOrder(arg1) {
  return window['go']['main']['App']['UpdateAssetOrder'](arg1);
}

export function UpdateCompendiumData(arg1) {
  return window['go']['main']['App']['UpdateCompendiumData'](arg1);
}

export function UpdateEntryTags(arg1, arg2) {
  return window['go']['main']['App']['UpdateEntryTags'](arg1, arg2);
}

export function UpdateOrder(arg1) {
  return window['go']['main']['App']['UpdateOrder'](arg1);
}

export function UpdateTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3, arg4);
}
