// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTagToEntry(arg1:number,arg2:number):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteEntry(arg1:number):Promise<void>;

export function DeleteMediaAsset(arg1:number):Promise<void>;

export function DeleteMediaGroup(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DownloadBackup(arg1:number):Promise<string>;

export function ExportMediaAsset(arg1:number,arg2:string):Promise<void>;

export function GetAllLibraryAssets():Promise<Array<main.MediaAsset>>;

export function GetAllTags():Promise<Array<main.Tag>>;

export function GetCompendiumData():Promise<main.CompendiumData>;

export function GetEntries(arg1:string):Promise<Array<main.MangaEntry>>;

export function GetEntryImage(arg1:number):Promise<string>;

export function GetMediaAssets(arg1:number):Promise<Array<main.MediaAsset>>;

export function GetMediaGroups(arg1:number):Promise<Array<main.MediaGroup>>;

export function GetTagsForEntry(arg1:number):Promise<Array<main.Tag>>;

export function ImportLegacyCSV():Promise<string>;

export function RemoveTagFromEntry(arg1:number,arg2:number):Promise<void>;

export function SaveEntry(arg1:main.MangaEntry):Promise<void>;

export function SaveMediaAsset(arg1:main.MediaAsset,arg2:string):Promise<void>;

export function SaveMediaGroup(arg1:main.MediaGroup):Promise<void>;

export function UpdateAssetOrder(arg1:Array<main.MediaAsset>):Promise<void>;

export function UpdateCompendiumData(arg1:main.CompendiumData):Promise<void>;

export function UpdateEntryTags(arg1:number,arg2:Array<number>):Promise<void>;

export function UpdateOrder(arg1:Array<main.MangaEntry>):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
